In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
import warnings 
warnings.filterwarnings("ignore")
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!git clone -b feature/add_hf https://github.com/nielsrogge/ImageBind.git
%cd ImageBind

Cloning into 'ImageBind'...
remote: Enumerating objects: 125, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 125 (delta 57), reused 39 (delta 39), pack-reused 40 (from 1)
Receiving objects: 100% (125/125), 2.64 MiB | 30.02 MiB/s, done.
Resolving deltas: 100% (59/59), done.
/kaggle/working/ImageBind


In [3]:
!pip install .

Processing /kaggle/working/ImageBind
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/facebookresearch/pytorchvideo.git (to revision 28fe037d212663c6a24f373b94cc5d478c8c1a1d) to /tmp/pip-install-j0iln_oc/pytorchvideo_a4e8380b57c94c708d06650a47ecd723
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorchvideo.git /tmp/pip-install-j0iln_oc/pytorchvideo_a4e8380b57c94c708d06650a47ecd723
  Running command git rev-parse -q --verify 'sha^28fe037d212663c6a24f373b94cc5d478c8c1a1d'
  Running command git fetch -q https://github.com/facebookresearch/pytorchvideo.git 28fe037d212663c6a24f373b94cc5d478c8c1a1d
  Running command git checkout -q 28fe037d212663c6a24f373b94cc5d478c8c1a1d
  Resolved https://github.com/facebookresearch/pytorchvideo.git to commit 28fe037d212663c6a24f373b94cc5d478c8c1a1d
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (

In [4]:
from imagebind import data
import torch
from imagebind.models import imagebind_model
from imagebind.models.imagebind_model import ModalityType
from imagebind.models.imagebind_model import ImageBindModel

text_list=["A dog.", "A car", "A bird"]
image_paths=[".assets/dog_image.jpg", ".assets/car_image.jpg", ".assets/bird_image.jpg"]
audio_paths=[".assets/dog_audio.wav", ".assets/car_audio.wav", ".assets/bird_audio.wav"]

device = "cuda:0" if torch.cuda.is_available() else "cpu"

model = ImageBindModel.from_pretrained("nielsr/imagebind-huge")
model.eval()
model.to(device)

# # Load data
# inputs = {
#     ModalityType.TEXT: data.load_and_transform_text(text_list, device),
#     ModalityType.VISION: data.load_and_transform_vision_data(image_paths, device),
#     ModalityType.AUDIO: data.load_and_transform_audio_data(audio_paths, device),
# }

# with torch.no_grad():
#     embeddings = model(inputs)

# print(
#     "Vision x Text: ",
#     torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.TEXT].T, dim=-1),
# )
# print(
#     "Audio x Text: ",
#     torch.softmax(embeddings[ModalityType.AUDIO] @ embeddings[ModalityType.TEXT].T, dim=-1),
# )
# print(
#     "Vision x Audio: ",
#     torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.AUDIO].T, dim=-1),
# )

# Expected output:
#
# Vision x Text:
# tensor([[9.9761e-01, 2.3694e-03, 1.8612e-05],
#         [3.3836e-05, 9.9994e-01, 2.4118e-05],
#         [4.7997e-05, 1.3496e-02, 9.8646e-01]])
#
# Audio x Text:
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])
#
# Vision x Audio:
# tensor([[0.8070, 0.1088, 0.0842],
#         [0.1036, 0.7884, 0.1079],
#         [0.0018, 0.0022, 0.9960]])


config.json:   0%|          | 0.00/844 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/4.80G [00:00<?, ?B/s]

ImageBindModel(
  (modality_preprocessors): ModuleDict(
    (vision): RGBDTPreprocessor(
      (cls_token): tensor((1, 1, 1280), requires_grad=True)
      
      (rgbt_stem): PatchEmbedGeneric(
        (proj): Sequential(
          (0): PadIm2Video()
          (1): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
        )
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 257, 1280), requires_grad=True)
        
      )
    )
    (text): TextPreprocessor(
      (pos_embed): tensor((1, 77, 1024), requires_grad=True)
      (mask): tensor((77, 77), requires_grad=False)
      
      (token_embedding): Embedding(49408, 1024)
    )
    (audio): AudioPreprocessor(
      (cls_token): tensor((1, 1, 768), requires_grad=True)
      
      (rgbt_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 768, kernel_size=(16, 16), stride=(10, 10), bias=False)
        (norm_layer): LayerNorm((768,), eps=1e-05, elementwise_affine=

In [5]:
entity_audio_dir = "/kaggle/input/business-json/entity_aud_files/kaggle/working/entity_aud_files"
sentence_audio_dir = '/kaggle/input/business-json/aud_files/kaggle/working/TTS/aud_files'

In [6]:
import ast
sentence_df = pd.read_csv('/kaggle/input/business-json/Test (1).csv') 
entity_df = pd.read_csv('/kaggle/input/business-json/entity_aud_files.csv')
ent_knowledge_df = pd.read_csv('/kaggle/input/business-json/Knowledge.csv')
sentence_df['entities'] = sentence_df['entities'].apply(lambda x: ast.literal_eval(x))

In [7]:
# import os
# import torch
# from imagebind.models import imagebind_model
# from imagebind.models.imagebind_model import ModalityType
# from imagebind.models.imagebind_model import ImageBindModel
# from imagebind import data
# import pandas as pd
# import ast


# entity_audio_paths = sorted([os.path.join(entity_audio_dir, f) for f in os.listdir(entity_audio_dir) if f.endswith('.wav')])
# sentence_audio_paths = sorted([os.path.join(sentence_audio_dir, f) for f in os.listdir(sentence_audio_dir) if f.endswith('.wav')])

# entity_names = entity_df['entity_name'].tolist()

# device = "cuda:0" if torch.cuda.is_available() else "cpu"

# # Load the data for text (entity names) and audio (entity and sentence audios)
# text_inputs = data.load_and_transform_text(entity_names, device)
# entity_audio_inputs = data.load_and_transform_audio_data(entity_audio_paths, device)
# sentence_audio_inputs = data.load_and_transform_audio_data(sentence_audio_paths, device)

# # Get embeddings
# with torch.no_grad():
#     embeddings = model({
#         ModalityType.TEXT: text_inputs,
#         ModalityType.AUDIO: torch.cat([entity_audio_inputs, sentence_audio_inputs], dim=0),
#     })

# # Separate entity and sentence embeddings
# entity_embeddings = embeddings[ModalityType.TEXT]
# audio_embeddings = embeddings[ModalityType.AUDIO]

# # Split audio embeddings into entity and sentence embeddings
# entity_audio_embeddings = audio_embeddings[:len(entity_audio_paths)]
# sentence_audio_embeddings = audio_embeddings[len(entity_audio_paths):]

# # Compute the ranking based on the formula: audio_features @ entity_text_features.T
# ranking_matrix = torch.matmul(sentence_audio_embeddings, entity_embeddings.T)

# # Rank entities based on the similarity scores
# rankings = torch.argsort(ranking_matrix, dim=-1, descending=True)

# # Function to calculate Top-N accuracy
# def calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1):
#     correct = 0
#     total = len(sentence_df)

#     # Create a map from entity name to entity ID
#     entity_map = dict(zip(entity_df['entity_name'], entity_df['ID']))

#     # Convert 'entities' column from string to list of dictionaries
#     sentence_df['entities'] = sentence_df['entities'].apply(lambda x: ast.literal_eval(x))

#     for idx, row in sentence_df.iterrows():
#         actual_entity_name = row['entities'][0]['mention']  # Get actual entity name
#         actual_entity_id = entity_map.get(actual_entity_name)  # Get corresponding ID
#         predicted_ranking = rankings[idx].tolist()  # Get the ranked indices for the sentence

#         # Get the actual entity's position in the ranking
#         actual_rank = predicted_ranking.index(entity_df[entity_df['ID'] == actual_entity_id].index[0])

#         # Check if the actual entity is within the top-n
#         if actual_rank < n:
#             correct += 1

#     return correct / total

# # Calculate Top-1, Top-5, and Top-10 accuracy
# top1_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1)
# top5_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=5)
# top10_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=10)

# print(f"Top-1 Accuracy: {top1_acc:.2f}")
# print(f"Top-5 Accuracy: {top5_acc:.2f}")
# print(f"Top-10 Accuracy: {top10_acc:.2f}")


In [8]:
# import gc
# torch.cuda.empty_cache()
# gc.collect()

In [13]:
import os
import torch
from imagebind.models.imagebind_model import ModalityType, ImageBindModel
from imagebind import data
import pandas as pd
from tqdm import tqdm
device = "cuda:0" if torch.cuda.is_available() else "cpu"

# Function to process audio files in batches
def process_audio_in_batches(audio_paths, text_inputs, batch_size=16):
    all_embeddings = []
    txt_embeddings = []
    for i in tqdm(range(0, len(audio_paths), batch_size), desc="Processing Batches"):
        batch_audio_paths = audio_paths[i:i + batch_size]
        audio_inputs = data.load_and_transform_audio_data(batch_audio_paths, device)
        if i == 0:
            with torch.no_grad():
                embeddings = model({
                    ModalityType.TEXT: text_inputs,
                    ModalityType.AUDIO: audio_inputs,
                })

            all_embeddings.append(embeddings[ModalityType.AUDIO])

            txt_embeddings.append(embeddings[ModalityType.TEXT])
        else:
            with torch.no_grad():
                embeddings = model({
                    ModalityType.AUDIO: audio_inputs,
                })

            all_embeddings.append(embeddings[ModalityType.AUDIO])
            
        # Clear CUDA cache to free up memory
        torch.cuda.empty_cache()
    
    return torch.cat(all_embeddings, dim = 0), txt_embeddings

# Get paths for entity and sentence audio files
entity_audio_paths = sorted([os.path.join(entity_audio_dir, f) for f in os.listdir(entity_audio_dir) if f.endswith('.wav')])
sentence_audio_paths = sorted([os.path.join(sentence_audio_dir, f) for f in os.listdir(sentence_audio_dir) if f.endswith('.wav')])

entity_names = entity_df['entity_name'].tolist()
entity_knowledge = ent_knowledge_df['Knowledge'].tolist()
# Load the data for text (entity names)
text_inputs = data.load_and_transform_text(entity_knowledge, device)

# Process entity audio files in batches
# entity_audio_embeddings,_ = process_audio_in_batches(entity_audio_paths, text_inputs)

# Process sentence audio files in batches
sentence_audio_embeddings, entity_embeddings  = process_audio_in_batches(sentence_audio_paths, text_inputs)



Processing Batches: 100%|██████████| 165/165 [02:22<00:00,  1.16it/s]


In [ ]:
# # Compute the ranking based on the formula: audio_features @ entity_text_features.T
# ranking_matrix = torch.matmul(sentence_audio_embeddings, entity_audio_embeddings.T)

# # Rank entities based on the similarity scores
# rankings = torch.argsort(ranking_matrix, dim=-1, descending=True)

# # Function to calculate Top-N accuracy
# def calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1):
#     correct = 0
#     total = len(sentence_df)

#     # Create a map from entity name to entity ID
#     entity_map = dict(zip(entity_df['entity_name'], entity_df['ID']))

#     # Convert 'entities' column from string to list of dictionaries


#     for idx, row in sentence_df.iterrows():
#         actual_entity_name = row['entities'][0]['mention']  # Get actual entity name
#         actual_entity_id = entity_map.get(actual_entity_name)  # Get corresponding ID
#         predicted_ranking = rankings[idx].tolist()  # Get the ranked indices for the sentence

#         # Get the actual entity's position in the ranking
#         actual_rank = predicted_ranking.index(entity_df[entity_df['ID'] == actual_entity_id].index[0])
#         print(actual_rank)
#         # Check if the actual entity is within the top-n 
#         if actual_rank < n: 
#             correct += 1
            
            
#     return correct / total
        
        
# top1_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1) 
# top5_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=5) 
# top10_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=10)

# print(f"Top-1 Accuracy: {top1_acc:.2f}") 
# print(f"Top-5 Accuracy: {top5_acc:.2f}") 
# print(f"Top-10 Accuracy: {top10_acc:.2f}")

In [14]:

# Compute the ranking based on the formula: audio_features @ entity_text_features.T
ranking_matrix = torch.matmul(sentence_audio_embeddings, entity_embeddings[0].T)

# Rank entities based on the similarity scores
rankings = torch.argsort(ranking_matrix, dim=-1, descending=True)

# Function to calculate Top-N accuracy
def calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1):
    correct = 0
    total = len(sentence_df)

    # Create a map from entity name to entity ID
    entity_map = dict(zip(entity_df['entity_name'], entity_df['ID']))

    for idx, row in sentence_df.iterrows():
        actual_entity_name = row['entities'][0]['mention']  # Get actual entity name
        actual_entity_id = entity_map.get(actual_entity_name)  # Get corresponding ID
        predicted_ranking = rankings[idx].tolist()  # Get the ranked indices for the sentence

        # Get the actual entity's position in the ranking
        actual_rank = predicted_ranking.index(ent_knowledge_df[entity_df['ID'] == actual_entity_id].index[0])

        # Check if the actual entity is within the top-n
        if actual_rank < n:
            correct += 1

    return correct / total

# Calculate Top-1, Top-5, and Top-10 accuracy
top1_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=1)
top5_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=5)
top10_acc = calculate_top_n_accuracy(rankings, sentence_df, entity_df, n=10)

print(f"Top-1 Accuracy: {top1_acc:.2f}")
print(f"Top-5 Accuracy: {top5_acc:.2f}")
print(f"Top-10 Accuracy: {top10_acc:.2f}")

Top-1 Accuracy: 0.00
Top-5 Accuracy: 0.01
Top-10 Accuracy: 0.02
